module.exports = {
  dbError: 'Database Error',
  userRegistered: 'User registered successfully',
  userNotRegistered: 'User registeration failed',
  invalidAPI: 'Invalid api endpoint',
  loginSuccess: 'Logged in successfully',
  loginFailed: 'Login Failed',
  invalidPass: 'Invalid password',
  invalidUser: 'Invalid user',
  userUpdated: 'User details updated successfully',
  userNotUpdated: 'User details not updated',
  unAuthorised: 'You can update only your accout ',
  tokenNotFound: 'Token not found',
  userDeleted: 'User deleted successfully',
  canNotDeleted: 'You can delete your account only',
  userFetched: 'User fetched successfully',
  notAllowToSeeAllUsers: 'You are not allowed to see all users',
  userStatsFetched: 'User stats fetched successfully',
  newMovieCreated: 'New movie created successfully',
  movieUpdated: 'Movie updated successfully',
  unAuthorisedToUpdateMovie: 'You are not authorised to update the movie',
  unAuthorisedToDeleteMovie: 'You are not authorised to delete the movie',
  movieDeleted: 'Movie has deleted successfully',
  randomMovieFound: 'Random Movie found successfully',
  moviesFetched: 'All movies fetched successfully',
  notAuthToFecthMovies: 'You are not authorised to get all movies',
  notAuthToCreateMovie: 'Your are not authorise to create movie',
  newListCreated: 'New list created successfully',
  notAuthToCreateList: 'You are not authorised to create new list',
  notAuthToDeleteList: 'You are not authorised to delete list',
  listDeleted: 'List deleted successfully',
  listFethed: 'Lists fetched successfully',
};
